# Generated by Django 2.2 on 2019-05-01 03:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dayoff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('01', 'ลากิจ'), ('02', 'ลาป่วย')], default='01', max_length=2)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('approve_status', models.CharField(choices=[('w8', 'รอการอนุมัติ'), ('no', 'ไม่อนุมัติ'), ('ok', 'อนุมัติ')], default='w8', max_length=2)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
