# Generated by Django 2.1.7 on 2019-04-15 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Polls',
            new_name='Poll',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='polls',
            new_name='poll',
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('01', 'Single answer'), ('02', 'Multiple answer')], default='01', max_length=2),
        ),
    ]
